java_library(
    name = "compositer",
    visibility = [
            "//src/main/java/com/kruglikov/pointilism/main:__pkg__",
        ],
    srcs = glob(["*.java"]),
    deps = [
            "//src/main/java/com/kruglikov/pointilism/index",
            "//src/main/java/com/kruglikov/pointilism/store",
    ],
)
