java_library(
    name = "store",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/kruglikov/pointilism/main:__pkg__",
    ],
    deps = [
        "//src/main/java/com/kruglikov/pointilism/index",
    ],
)
