java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/kruglikov/pointilism/index:__pkg__",
        "//src/main/java/com/kruglikov/pointilism/main:__pkg__",
        "//src/main/java/com/kruglikov/pointilism/store:__pkg__",
    ],
)
